### ISSUE TITLE
🌐 API Roadmap

### ISSUE THREAD

**Issue by R1013-T** [TECH-C-LT/Peace-Net#21]
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/3
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/47
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/14
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/20
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/5
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/6
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/78
