### ISSUE TITLE
🕸️ Web Roadmap

### ISSUE THREAD

**Issue by R1013-T** [TECH-C-LT/Peace-Net#22]
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/11
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/7
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/12
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/10
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/13
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/15
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/16
