### ISSUE TITLE
DB Roadmap

### ISSUE THREAD

**Issue by R1013-T** [TECH-C-LT/Peace-Net#33]
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/8
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/9
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/32
