### ISSUE TITLE
✌️ Peace Net ✌️

### ISSUE THREAD

**Issue by R1013-T** [TECH-C-LT/Peace-Net#35]
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/36
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/2
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/22
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/21
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/31
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/34
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/19
- [x] https://github.com/TECH-C-LT/Peace-Net/issues/37

**Comment by R1013-T** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
